services:
  datagen:
    build: .
    container_name: datagen-dev
    volumes:
      - .:/app
      - datagen-cache:/root/.cache
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  datagen-cache: